.TH IM_ANALYZE2VIPS 3 "4 August 2005"
.SH NAME
im_analyze2vips \- convert Analyze 7.5 images to VIPS format
.SH SYNOPSIS
#include <vips/vips.h>

int im_analyze2vips( const char *filename, IMAGE *out )

int im_analyze2vips_header( const char *filename, IMAGE *out )

.SH DESCRIPTION
.B im_analyze2vips(3) 
reads the Analyze image in 
.B filename, 
and writes the image out
in VIPS format. It can read (almost) any Analyze format image. Images with
more than two dimensions simply appear as a very tall, thin strip. Use 
.B im_grid(3)
to lay the tiles out as your prefer. 

It reads the old-style 7.5 format, where the header and the image data are
stored in separate files. You can give the name of either the header (for
example, "fred.hdr") the image data (for example, "fred.img"), or neither (eg.
"fred").

The fields in the Analyze header appear in the VIPS header with a "dsr-"
prefix. So the Analyze field "patient_id", which is part of data_history, may
be retrieved with

  im_header_string "dsr-data_history.patient_id" fred.v

.B im_analyze2vips_header() 
reads the just the header of the image into the VIPS image. You can't read any
pixels!

.SH SEE ALSO
im_grid(3)
.SH COPYRIGHT
Imperial College 2005
