.TH IM_VIPS2MASK 3 "6 June 1994"
.SH NAME
im_vips2mask, im_mask2vips \- convert between masks and images
.SH SYNOPSIS
.B #include <vips/vips.h>

DOUBLEMASK *im_vips2mask( IMAGE *in, char *out_name )

int im_mask2vips( DOUBLEMASK *in, IMAGE *out )
.SH DESCRIPTION
.B im_vips2mask(3)
returns a DOUBLEMASK of name out_name containing the data from IMAGE in.
Images must have either one band, a width of 1, or a height of 1. 
Returns NULL on error, and a new mask on success.
The scale field is set to 1.0 and the offset to 0.0.

.B im_mask2vips(3)
writes the doubles held in mask in to the IMAGE out. It creates a one-band
image of the same size as in. It returns 0 on success and -1 on error. The
scale and offset fields are ignored.

.SH SEE ALSO
im_openin(3), im_openout(3), im_setbuf(3), edvips(3), im_create_dmask(3).
.SH COPYRIGHT
.br
National Gallery, 1994
