.TH BATCH_IMAGE_CONVERT 1 "2 Feb 2002"
.SH NAME
batch_image_convert  \- use VIPS to convert a set of images to a new type
.SH SYNOPSIS
.B batch_image_convert type image1 image2 ...
.SH DESCRIPTION
The first argument is the name of an image type, subsequent arguments are
the names of files to be converted to that type. VIPS can usually read almost
any image type, but it can only write VIPS, PNG, TIFF, PPM/PGM/PBM and JPEG.
You can specify conversion parameters in the type name.

For example:

  batch_image_convert tiff fred.jpg jim.png

will convert
.B fred.jpg
and
.B jim.png
to TIFF format.

  batch_image_convert jpeg:95 jim.png

will write jim.jpeg with a 95% quality factor.
.SH RETURN VALUE
returns 0 on success and non-zero on error.
.SH SEE ALSO
header(1), im_vips2tiff(3), im_vips2jpeg(3), im_vips2png(3), im_vips2ppm(3)

