.TH HEADER 1 "12 July 1990"
.SH NAME
header \- prints information about an image file
.SH SYNOPSIS
header [OPTIONS ...] files ...
.SH DESCRIPTION
.B header(1)
prints image header fields to stdout.

.SH OPTIONS
.TP
.B -f FIELD, --field=FIELD
Print value of 
.B FIELD 
from image header. The special field name getext prints
the VIPS extension block: the XML defining the image metadata. You can alter
this, then reattach with 
.B edvips(1).

.TP
.B -a, --all
Show all fields. Normally 
.B header
just shows a one-line summary.

.SH EXAMPLES
 $ header -f Xsize ~/pics/*.v   
 1024
 1279
 22865
 1
 256

.SH SEE ALSO
edvips(1)
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 12/07/1990
