.TH IM_BLACK 3 "11 April 1990"
.SH NAME
im_black \- make a black image
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_black(out, x, y, bands)
.br
.B IMAGE *out;
.br
.B int x, y, bands;
.SH DESCRIPTION
im_black()
makes a black uchar image of the specified size and number of bands.
.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE\ ALSO
im_openin(3), im_openout(3), im_setbuf(3).
.SH COPYRIGHT
.br
National Gallery 1990 - 1993
.SH AUTHOR
J. Cupitt \- 11/04/1990
