.TH im_dE_fromLab 3 "2 December 1992"
.SH NAME
im_dE_fromLab, im_dECMC_fromLab, im_dE00_fromLab \- calculate colour differences
.SH SYNOPSIS
#include <vips/vips.h>

int im_dE_fromLab(in1, in2, out)
.br
IMAGE *in1, *in2, *out;

int im_dECMC_fromLab(in1, in2, out)
.br
IMAGE *in1, *in2, *out;

int im_dE00_fromLab(in1, in2, out)
.br
IMAGE *in1, *in2, *out;

.SH DESCRIPTION
Given a pair of images in Lab format, these functions calculate CIE76,
CMC(1:1) and CIEDE2000 colour difference images.  These are the basic colour 
difference
calculators in VIPS --- other colour difference functions, such as
.B im_dE_fromXYZ(3), 
are provided as a convenience to the programmer.

See 
.B im_Lab2XYZ(3)
for an explanation of the various colour spaces VIPS
supports and how to convert between them.

.SH RETURN VALUE
The functions return 0 on success and -1 on error.
.SH SEE ALSO
im_col_XYZ2rgb(3), im_XYZ2rgb(3), im_dE_fromXYZ(3).
.SH COPYRIGHT
National Gallery, 1990 - 1993
.SH AUTHOR
J.Ph. Laurent \- 2/12/1992
.br
J. Cupitt \- 21/7/93

