.TH IM_DE_FROMDISP 3 "2 December 1992"
.SH NAME
im_dE_fromdisp, im_dE_fromXYZ, im_dECMC_fromdisp \- derived colour difference
functions
.SH SYNOPSIS
#include <vips/vips.h>

im_dE_fromdisp( in1, in2, out, display )
.br
IMAGE *in1, *in2, *out;
.br
struct im_col_display *display;

int im_dE_fromXYZ(in, out)
.br
IMAGE *in, *out;

im_dECMC_fromdisp( in1, in2, out, display )
.br
IMAGE *in1, *in2, *out;
.br
struct im_col_display *display;

.SH DESCRIPTION
These functions are built on the basic VIPS colour difference measurements as a
convenience for the programmer. See im_dE_fromLab(3) for an explanation of the
colour difference metrics and the basic comparision functions.

.SH RETURN VALUE
The functions return 0 on success and -1 on error.
.SH SEE ALSO 
im_col_XYZ2rgb(3), im_dE_fromLab(3), im_LabQ2Lab(3), im_Lab2disp(3).
.SH COPYRIGHT
National Gallery and Birkbeck College, 1990 - 1993
.SH AUTHOR
K. Martinez \- 2/12/1992
.br
J. Cupitt \- 21/7/93
