.TH DIVISION 3 "24 April 1991"
.SH NAME
im_divide \- divide two images
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_divide(in1, in2, out)
.br
.B IMAGE *in1, *in2, *out;

.SH DESCRIPTION
.B im_divide(3)
divides two images. The result is float except if one (or both) input is
double.  In the latter case the result is double. If either input is complex,
the result is complex. If either input is double complex, the output is double
complex.

Input images in1 and in2 should have the same channels and the same sizes,
however they can be of different types.  

For complex input pels (x1,y1) and (x2,y2), 
.B im_divide(3) 
calculates
  ((x1*x2 + y1*y2)/(x2*x2 + y2*y2), (y1*x2 - x1*y2)/(x2*x2 + y2*y2)).

.SH BUGS
The function does not check the result for over/underflow.
.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE\ ALSO
im_remainder(3), im_multiply(3), im_subtract(3), im_lintra(3), im_add(3).
.SH COPYRIGHT
National Gallery, 1995
