.TH IM_FALSECOLOUR 3 "30 October 1992"
.SH NAME
im_falsecolour \- colour a mono image
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_falsecolour(in, out)
.br
.B IMAGE *in, *out;

.SH DESCRIPTION
Turns a one-band unsigned char image into a three band unsigned char image.
The colour scale is stolen from a PET scan and has red for hot, green for
normal and blue for cold.
.SH RETURN VALUE
0 on success and -1 on error.
.SH SEE ALSO
im_disp2XYZ(3), etc.
.SH COPYRIGHT
.br
National Gallery
.SH AUTHOR
J. Cupitt
