.TH IM_INVERT 3 "11 April 1990"
.SH NAME
im_invert \- inverts an image pointed by an image descriptor.
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_invert(in, out)
.br
.B IMAGE *in, *out;
.SH DESCRIPTION
.B im_invert
inverts the image held by image descriptor in and writes the result on the 
image descriptor out.  The function works on FMTUCHAR images only.  
The result at point x of the input image is 255-x at the output image.
Input can have any no of channels.
.br
  This is not a generally useful program -- it is included as an example of a
very simple new-style IO function. Feel the power of the source, Luke!
.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE\ ALSO
im_add(3), im_lintra(3), im_multiply(3).
.SH AUTHOR
J. Cupitt \- 21/7/93
