.TH IM_OPENOUT 3 "22 April 1991"
.SH NAME
im_openout \- sets an image descriptor corresponding to an output file
.SH SYNOPSIS
.B #include <vips/vips.h>

.B IMAGE *im_openout(file_name)
.br
.B char *file_name;
.SH DESCRIPTION
.B im_openout(3)
returns a descriptor which when written to will write pels to file_name. This
function has been replaced by im_open(3).
.SH RETURN VALUE
The function returns a valid image descriptor on success and NULL on error.
.SH SEE\ ALSO
im_open(3), im_close(3), im_mmapin(3), im_intro(3).
.SH COPYRIGHT
.br
N. Dessipris
.SH AUTHOR
N. Dessipris \- 22/04/1991
