.TH IM_PPM 3 "November 2000"
.SH NAME
im_ppm2vips, im_vips2ppm \- convert PPM/PGM/PBM images to and from VIPS format
.SH SYNOPSIS
#include <vips/vips.h>

int im_ppm2vips( const char *filename, IMAGE *out )

int im_vips2ppm( IMAGE *in, const char *filename )

.SH DESCRIPTION
.B im_ppm2vips(3) 
reads the PPM/PGM/PBM image in filename, and writes the image out
in VIPS format. It can read 1, 8, 16 and 32 bit images, colour or monochrome,
stored in binary or in ASCII. One bit images become 8 bit VIPS images, with 0
and 255 for 0 and 1.

.B im_vips2ppm(3) 
writes the VIPS image to the named file in PPM format. It can write 8, 16 or
32 bit integer images, colour or monochrome, stored as binary or ASCII. Images
of more than 8 bits can only be stored in ASCII.

The storage format is indicated by a filename extension.

  im_vips2ppm( im, "fred.ppm:ascii" )

will write to "fred.ppm" in ascii format. The default is binary.

.SH SEE ALSO
im_open(3)
.SH COPYRIGHT
Hey, you want this? You have it!
