.TH IM_RAD2FLOAT 3 "25 March 2009"
.SH NAME
im_rad2float, im_float2rad \- convert RAD coded images to float and back
.SH SYNOPSIS
#include <vips/vips.h>

int im_rad2float( IMAGE *in, IMAGE *out )

int im_float2rad( IMAGE *in, IMAGE *out )

.SH DESCRIPTION
These functions convert 
.B IM_CODING_RAD 
images to 3-band float and back.

.B im_rad2float(3)
unpacks a 4-band uchar image in
.B IM_CODING_RAD
format to 3-band float. RAD images are used by the 
.B radiance(1)
family of programs for HDR imaging. 

Some VIPS operations will work directly on the packed RAD images (such as 
.B im_extract_area(3)
) but many will require the image to be unpacked to 3-band float for
processing.

.B im_float2rad(3)
packs a 3-band float image back to 4-band uchar in
.B IM_CODING_RAD
format.

.SH RETURN VALUE
The functions return 0 on success and -1 on error.
.SH SEE ALSO
im_LabQ2Lab(3), im_format(3).
.SH AUTHOR
J. Cupitt \- 23 March 2009
