.TH IM_SMUDGE 3 "30 October 1992"
.SH NAME
im_smudge, im_smear \- filter and smudge in place
.SH SYNOPSIS
.B #include <vips/vips.h>
.br
.B #include <vips/rect.h>

int
.br
im_smudge( im, ix, iy, r )
.br
IMAGE *im;
.br
int ix, iy;
.br
Rect *r;

int
.br
im_smear( im, ix, iy, r )
.br
IMAGE *im;
.br
int ix, iy;
.br
Rect *r;
.SH DESCRIPTION
im_smudge() performs a low-pass filter of the pels inside rect r. Rect r is
clipped against the edges of the image. im_smear() is not very useful.

Both these functions are `in place,' that is, they write directly to the
output image! Be very careful, you can destroy data.
.SH RETURN VALUE
All functions return 0 on success and -1 on error.
.SH SEE\ ALSO
im_insertplace(3), im_readpoint(3).
.SH COPYRIGHT
.br
National Gallery, 1992
.SH AUTHOR
J. Cupitt
