.TH IM_SUBSAMPLE 3 "19 Aug 1996"
.SH NAME
im_subsample \- subsample image by integer factor
.SH SYNOPSIS
#include <vips/vips.h>

int im_subsample(in, out, xsub, ysub)
.br
IMAGE *in, *out;
.br
int xsub, ysub;

.SH DESCRIPTION
.B im_subsample()
sub-samples image in by an x and y integer factor. It is much faster than
im_shrink(), especially for large partial images.

It works for any image type.
.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_shrink(3), im_similarity(3), im_zoom(3)
.SH COPYRIGHT
1989-1996 The National Gallery and Birkbeck College
