.TH VIDEO 3 "3 March 2001"
.SH NAME
im_video_v4l1 \- various image grabbers

.SH SYNOPSIS
.B #include <vips/vips.h>

.B int 
.B im_video_v4l1( IMAGE *im, const char *device, int channel, 
.B   int brightness, int colour, int contrast, int hue,
.B   int ngrabs )

.SH DESCRIPTION
These functions grab single video frames from various devices. Which of these
functions work depends upon how your VIPS has been configured and compiled,
and your platform. As a result, they are far from portable ... you want a
layer on top of these functions.

.B im_video_v4l1(3)
grabs a frame using Video4Linux. It grabs a 24-bit RGB colour image, at the
maximum resolution your card allows. 

.B device
should typically be "/dev/video".
.B channel
selects the channel to acquire: usually 0 is TV, and 1 is composite video.
.B brightness,
.B colour,
.B contrast 
and
.B hue 
set grab parameters. Each should be in the range (0 - 32768). 32768 is usually
the value you want.
.B ngrabs
sets the number of frames the card should average. Higher values are slower,
but typically less noisy (and slightly softer).

.SH RETURN VALUE
All functions return 0 on success and -1 on error.
