.TH IM_ZONE 3 "10 May 1991"
.SH NAME
im_zone, im_fzone \- creates a zone plate
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_zone(image, size)
.br
.B IMAGE *image;
.br
.B int size;

.B int im_fzone(image, size)
.br
.B IMAGE *image;
.br
.B int size;

.SH DESCRIPTION

.B im_fzone()
creates a float one band image of a zone plate of size size by size. Pels are
in the range [-1,+1]. The zone plate has spatial frequencies increasing from
0 the center (at size/2, size/2) up to infinity at the edges. size must be
positive and even.

.B im_zone()
behaves exactly as im_fzone(), but writes a FMTUCHAR image scaled to the range
0-255. 

.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_grey(3), im_fgrey(3).
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 10/05/1991
