.TH IM_ZOOM 3 "11 April 1990"
.SH NAME
im_zoom \- zoom an image 
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_zoom(in, out, xfac, yfac)
.br
.B IMAGE *in, *out;
.B int xfac, yfac;

.SH DESCRIPTION
.B im_zoom()
zooms (ie. nearest neighbour upsampling) the image held by the image
descriptor in by factors xfac and yfac and writes the result to the image
descriptor out.  Works for any type of image, even LABPACK.

.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_copy(3), im_affine(3).
.SH COPYRIGHT
National Gallery, 1994.
