.TH SIMCONTR 1 "27 January 1992"
.SH NAME
simcontr \- shows the effect of simultaneous contrast
.SH SYNOPSIS
.B simcontr image xsize ysize
.SH DESCRIPTION
.B simcontr
creates an unsigned char one band grey scale image of sizes xsize by ysize.
The created pattern consists of two neighbouring squares one dark (left
square) and one light (right square).  The left 
one contains a smaller light square and the right
one contains a darker square.
.SH SEE\ ALSO
grey(1)
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 27/02/1992
