BEGIN {
D["PACKAGE_NAME"]=" \"vips\""
D["PACKAGE_TARNAME"]=" \"vips\""
D["PACKAGE_VERSION"]=" \"8.8.0\""
D["PACKAGE_STRING"]=" \"vips 8.8.0\""
D["PACKAGE_BUGREPORT"]=" \"vipsip@jiscmail.ac.uk\""
D["PACKAGE_URL"]=" \"\""
D["PACKAGE"]=" \"vips\""
D["VERSION"]=" \"8.8.0\""
D["G_LOG_DOMAIN"]=" \"VIPS\""
D["VIPS_ICC_DIR"]=" \"/usr/share/color/icc\""
D["VIPS_PREFIX"]=" \"/home/john/vips\""
D["VIPS_LIBDIR"]=" \"/home/john/vips/lib\""
D["GETTEXT_PACKAGE"]=" \"vips8.8\""
D["STDC_HEADERS"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_MEMORY_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_LOCALE_H"]=" 1"
D["HAVE_LC_MESSAGES"]=" 1"
D["HAVE_BIND_TEXTDOMAIN_CODESET"]=" 1"
D["HAVE_GETTEXT"]=" 1"
D["HAVE_DCGETTEXT"]=" 1"
D["ENABLE_NLS"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["STDC_HEADERS"]=" 1"
D["HAVE_ERRNO_H"]=" 1"
D["HAVE_MATH_H"]=" 1"
D["HAVE_FCNTL_H"]=" 1"
D["HAVE_LIMITS_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_SYS_FILE_H"]=" 1"
D["HAVE_SYS_IOCTL_H"]=" 1"
D["HAVE_SYS_PARAM_H"]=" 1"
D["HAVE_SYS_TIME_H"]=" 1"
D["HAVE_SYS_MMAN_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_DLFCN_H"]=" 1"
D["LT_OBJDIR"]=" \".libs/\""
D["restrict"]=" __restrict"
D["HAVE_VAR_ATTRIBUTE_VECTOR_SIZE"]=" 1"
D["HAVE_VECTOR_SHUFFLE"]=" 1"
D["HAVE_VECTOR_ARITH"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_SYS_PARAM_H"]=" 1"
D["HAVE_GETPAGESIZE"]=" 1"
D["HAVE_MMAP"]=" 1"
D["HAVE_VPRINTF"]=" 1"
D["HAVE_GETCWD"]=" 1"
D["HAVE_GETTIMEOFDAY"]=" 1"
D["HAVE_GETWD"]=" 1"
D["HAVE_MEMSET"]=" 1"
D["HAVE_MUNMAP"]=" 1"
D["HAVE_PUTENV"]=" 1"
D["HAVE_REALPATH"]=" 1"
D["HAVE_STRCASECMP"]=" 1"
D["HAVE_STRCHR"]=" 1"
D["HAVE_STRCSPN"]=" 1"
D["HAVE_STRDUP"]=" 1"
D["HAVE_STRERROR"]=" 1"
D["HAVE_STRRCHR"]=" 1"
D["HAVE_STRSPN"]=" 1"
D["HAVE_VSNPRINTF"]=" 1"
D["HAVE_REALPATH"]=" 1"
D["HAVE_MKSTEMP"]=" 1"
D["HAVE_MKTEMP"]=" 1"
D["HAVE_RANDOM"]=" 1"
D["HAVE_RAND"]=" 1"
D["HAVE_SYSCONF"]=" 1"
D["HAVE_ATEXIT"]=" 1"
D["HAVE_CBRT"]=" 1"
D["HAVE_HYPOT"]=" 1"
D["HAVE_ATAN2"]=" 1"
D["HAVE_CONTEXT_GET_HELP"]=" 1"
D["HAVE_MONOTONIC_TIME"]=" 1"
D["HAVE_MUTEX_INIT"]=" 1"
D["HAVE_COND_INIT"]=" 1"
D["HAVE_THREAD_NEW"]=" 1"
D["HAVE_PRIVATE_INIT"]=" 1"
D["HAVE_VALUE_GET_SCHAR"]=" 1"
D["HAVE_G_STR_TO_ASCII"]=" 1"
D["HAVE_CHECKED_MUL"]=" 1"
D["HAVE_EXPAT_H"]=" 1"
D["HAVE_GSF"]=" 1"
D["HAVE_GSF_ZIP64"]=" 1"
D["HAVE_GSF_DEFLATE_LEVEL"]=" 1"
D["HAVE_FFTW"]=" 1"
D["HAVE_MAGICK6"]=" 1"
D["HAVE_SETIMAGEOPTION"]=" 1"
D["HAVE_SETIMAGEOPTION"]=" 1"
D["HAVE_MAGICKCOREGENESIS"]=" 1"
D["HAVE_MAGICKCOREGENESIS"]=" 1"
D["HAVE_RESETIMAGEPROPERTYITERATOR"]=" 1"
D["HAVE_RESETIMAGEPROPERTYITERATOR"]=" 1"
D["HAVE_RESETIMAGEATTRIBUTEITERATOR"]=" 1"
D["HAVE_RESETIMAGEATTRIBUTEITERATOR"]=" 1"
D["HAVE_RESETIMAGEPROFILEITERATOR"]=" 1"
D["HAVE_RESETIMAGEPROFILEITERATOR"]=" 1"
D["HAVE_GETVIRTUALPIXELS"]=" 1"
D["HAVE_GETVIRTUALPIXELS"]=" 1"
D["HAVE_NUMBER_SCENES"]=" 1"
D["HAVE_ACQUIREIMAGE"]=" 1"
D["HAVE_ACQUIREIMAGE"]=" 1"
D["HAVE_SETIMAGEEXTENT"]=" 1"
D["HAVE_SETIMAGEEXTENT"]=" 1"
D["HAVE_SETIMAGEPROPERTY"]=" 1"
D["HAVE_SETIMAGEPROPERTY"]=" 1"
D["HAVE_BLOBTOSTRINGINFO"]=" 1"
D["HAVE_BLOBTOSTRINGINFO"]=" 1"
D["HAVE_INHERITEXCEPTION"]=" 1"
D["HAVE_INHERITEXCEPTION"]=" 1"
D["HAVE_ACQUIREEXCEPTIONINFO"]=" 1"
D["HAVE_ACQUIREEXCEPTIONINFO"]=" 1"
D["HAVE_IMPORTIMAGEPIXELS"]=" 1"
D["HAVE_IMPORTIMAGEPIXELS"]=" 1"
D["HAVE_IMAGESTOBLOB"]=" 1"
D["HAVE_IMAGESTOBLOB"]=" 1"
D["ENABLE_MAGICKLOAD"]=" 1"
D["ENABLE_MAGICKSAVE"]=" 1"
D["HAVE_ORC"]=" 1"
D["HAVE_ORC_PROGRAM_GET_ERROR"]=" 1"
D["HAVE_ORC_PROGRAM_GET_ERROR"]=" 1"
D["HAVE_LCMS2"]=" 1"
D["HAVE_OPENEXR"]=" 1"
D["HAVE_NIFTI"]=" 1"
D["HAVE_POPPLER"]=" 1"
D["HAVE_RSVG"]=" 1"
D["HAVE_ZLIB"]=" 1"
D["HAVE_OPENSLIDE_3_4"]=" 1"
D["HAVE_OPENSLIDE"]=" 1"
D["HAVE_MATIO"]=" 1"
D["HAVE_PPM"]=" 1"
D["HAVE_ANALYZE"]=" 1"
D["HAVE_RADIANCE"]=" 1"
D["HAVE_CFITSIO"]=" 1"
D["HAVE_LIBWEBP"]=" 1"
D["HAVE_PANGOFT2"]=" 1"
D["HAVE_TIFF"]=" 1"
D["HAVE_GIFLIB"]=" 1"
D["HAVE_PNG"]=" 1"
D["HAVE_JPEG"]=" 1"
D["HAVE_EXIF"]=" 1"
D["UNTAGGED_EXIF"]=" 1"
  for (key in D) D_is_set[key] = 1
  FS = ""
}
/^[\t ]*#[\t ]*(define|undef)[\t ]+[_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ][_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]*([\t (]|$)/ {
  line = $ 0
  split(line, arg, " ")
  if (arg[1] == "#") {
    defundef = arg[2]
    mac1 = arg[3]
  } else {
    defundef = substr(arg[1], 2)
    mac1 = arg[2]
  }
  split(mac1, mac2, "(") #)
  macro = mac2[1]
  prefix = substr(line, 1, index(line, defundef) - 1)
  if (D_is_set[macro]) {
    # Preserve the white space surrounding the "#".
    print prefix "define", macro P[macro] D[macro]
    next
  } else {
    # Replace #undef with comments.  This is necessary, for example,
    # in the case of _POSIX_SOURCE, which is predefined and required
    # on some systems where configure will not decide to define it.
    if (defundef == "undef") {
      print "/*", prefix defundef, macro, "*/"
      next
    }
  }
}
{ print }
