.TH IM_FMASKPROF 3 "8 Oct 1991"
.SH NAME
im_flt_imag_freq \- filter a square image in the frequency domain
.SH SYNOPSIS
#include <vips/vips.h>

int 
.br
im_flt_imag_freq( IMAGE *in,  IMAGE *out, int flag, double p1, ... )

.SH DESCRIPTION
im_flt_imag_freq()
filters an image in the frequency domain using a mask dictated by the flag
and the parameters p1, ...  The mask is created by using the
function im_create_fmask(3).  After creating the mask the program filters
the input image using the function im_freqflt(3).

For details about the arguments refer to the function im_create_fmask(3).

.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_freqflt(3).
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 10/08/1991
