.TH IM_EYE 3 "10 May 1991"
.SH NAME
im_eye, im_feye \- creates a pattern which shows the spatial response of the human visual system
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_eye(image, xsize, ysize, factor)
.br
.B IMAGE *image;
.br
.B int xsize, ysize;
.br
.B double factor;

.B int im_feye(image, xsize, ysize, factor)
.br
.B IMAGE *image;
.br
.B int xsize, ysize;
.br
.B double factor;

.SH DESCRIPTION
.B im_feye()
creates an one band float image with pels in [-1,+1] of a pattern which has 
the following properties:
.br
- the spatial frequency increases from left to right.
.br
- the grey level intensity decreases from top to bottom.
.br
The sizes of the produced image are determined by the entered arguments
xsize and ysize.  The variable factor which should be between 0 and 1,
determines the number of maximum spatial frequencies present along the
horizontal direction.

.B im_eye()
behaves exactly as im_feye(), but scales the output to [0,255].

.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_grey(3), im_zone(3).
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 10/05/1991
