.TH IM_GREY 3 "10 May 1991"
.SH NAME
im_grey, im_fgrey, im_make_xy \- creates a grey scale 
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_grey( image, xsize, ysize )
.br
.B IMAGE *image;
.br
.B int xsize, ysize;

.B int im_fgrey( image, xsize, ysize )
.br
.B IMAGE *image;
.br
.B int xsize, ysize;

.B int im_make_xy( image, xsize, ysize )
.br
.B IMAGE *image;
.br
.B int xsize, ysize;

.SH DESCRIPTION
.B im_grey(3) 
creates a one-band FMTUCHAR grey scale image of sizes xsize by
ysize.  The intensity varies from 0 (left) to 255 (right).

.B im_fgrey(3) 
works as 
.B im_grey(3), 
except that the output image is FMTFLOAT,
allowing pixel values from 0 (left) to 1.0 (right).

.B im_make_xy(3) 
makes a two-band FMTUINT image where each pixel in band 0 has a value equal to
the x coordinate, and each pixel in band 1 has a value equal to the y
coordinate.

.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_black(3)
.SH COPYRIGHT
Birkbeck College and the National Gallery, 1995
