.TH IM_BITS_OF_FMT 3 "2 June 2005"
.SH NAME
im_bits_of_fmt \- return number of bits of band format
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_bits_of_fmt( int bandfmt )

.SH DESCRIPTION
.B im_bits_of_fmt(3)
calculates the number of bits of band format.

.SH RETURN VALUE
On success this function returns the number of bits of band format and
-1 is returned on error.

