.TH IM_DEBUG 3 "22 April 1991"
.SH NAME
im_debug, im_printlines \- print raw image data pointed by an image descriptor
.SH SYNOPSIS
.B #include <vips/vips.h>

.B void im_debugim( image )
.br
.B IMAGE *image;

.B void im_printlines( image )
.br
.B IMAGE *image;
.SH DESCRIPTION
.B im_debugim(3)
prints to the standard error output raw data pointed by image sequentially.
Data are printed as float numbers and the function interprets the input format
properly.  If input is complex then for each pixel the real part followed
by the imaginary is printed.  It can be used for debugging preferably on small
images. If input is uchar then the printed values are integers.

.B im_printlines
printes in the standard error output the no of line followed by CR, followed
by the line pixel values.  For each pixel, the x location
followed by the pixel value(s) is printed.  The location and the pixels value(s)
are separated by a tab.  Each pixel is printed on a separate line.
.SH COPYRIGHT
.br
N. Dessipris
.SH AUTHOR
N. Dessipris \- 22/04/1991
