.TH IM_CORREL 3 "13 May 1991"
.SH NAME
im_correl \- search for image match
.SH SYNOPSIS
#include <vips/vips.h>

int
.br
im_correl( IMAGE *ref, IMAGE *sec,
.br
  int xref, int yref, int xsec, int ysec,
.br
  int hwindowsize, int hsearchsize,
.br
  double *correlation, int *x, int *y )

.SH DESCRIPTION
im_correl() is the base image-searching function used by the mosaicing
functions im_lrmosaic() and im_tbmosaic(), and by the matching funtions
im_match_linear() and im_match_linear_search().

It finds the position of the secondary image 
.B sec 
within 
.B ref.
It searches the area around 
.B xsec
, 
.B ysec
for the best match for the area around
.B xref
, 
.B yref.
It searches an area of size
.B hsearchsize
for a match of size
.B hwindowsize.
The position of the best match is returned, together with the correlation at
that point.

Only the first band of each image is correlated. ref and sec may be very large
--- the function extracts and generated just the parts needed. Correlation is
done with im_spcor(); the position of the maximum is found with im_maxpos().
.SH SEE ALSO
im_fastcor(3), im_spcor(3), im_maxpos(3), im_match_linear(3), im_lrmosaic(3).
.SH AUTHOR
J.Cupitt \- 22/02/93
.SH COPYRIGHT
The National Gallery and Birkbeck College, 1989-1996.
