.TH VDUMP 1 "July 1990"
.SH NAME
vdump \- convert VIPS image files to Postscript
.SH SYNOPSIS
.B vdump 
[
.B \-slpDa
]
.IR filename
.SH DESCRIPTION
.B vdump
turns the vasari format file in its argument to encapsulated PostScript on its 
stadard output. The result can be
either sent directly to a printer or included in any document processor which
supports encapsulated PostScript diagrams - eg. WordPerfect, Tex etc. For 
example:
.IP
.B
example% vdump campin.v | lpr -Plaser
.LP
or
.IP
.B
example% vdump -l -s4 -D campin.v > campin.PS
.LP
.br
.B vdump
normally outputs portrait, you can force output to portrait or landscape with the 
.BR \-p 
or 
.BR \-l 
flags.

.br
The
.BR \-a
flag makes vdump select 
either portrait or landscape orientation so as to get
the largest possible image onto an A4 sheet.  

.br
.B vdump
will dump one or three band unsigned char images only.
.SH OPTIONS
.TP
.B \-p
Force portrait output.
.TP
.B \-l
Force landscape output.
.TP
.B \-a
Automatically select portrait/landscape.
.TP
.B \-s<factor>
Set a sub-sampling factor (default 1).
.BR \-s1
will not sub-sample at all,
.BR \-s4
will reduce by a factor of 4. 
.TP
.B \-D
Produce output suitable for including in documents. This option
simply supresses the generation of a showpage command.
.SH SEE\ ALSO
ip(1), vips2dj(1)
.SH COPYRIGHT
.br
1990: J. Cupitt, National Gallery
