.TH DEBUGIM 1 "12 July 1990"
.SH NAME
debugim, printlines \- prints the raw image data of a vasari file format
.SH SYNOPSIS
debugim infile

printlines infile
.SH DESCRIPTION
debugim prints at the standard error output the raw image data of a vasari
format file.  This function is useful for debugging when applied on small
image files

printlines prints at the standard error output the raw image data of a vasari
format together with the line no and the x location and the value(s) of each
pixel.
.SH SEE ALSO
im_intro(3X), im_debugim(3X), im_printlines(3X), vips2mask(1X).
.SH COPYRIGHT
N. Dessipris
.SH AUTHOR
N. Dessipris \- 12/07/1990
