.TH IM_CONTRAST_SURFACE 3 "01 May 2006"
.SH NAME
 im_contrast_surface, im_contrast_surface_raw \- Generate contrast surface
.SH SYNOPSIS
.nf
.B #include <vips/vips.h>
.sp
.BI "int im_contrast_surface( IMAGE " "*in" ", IMAGE " "*out" ", int " "half_win_size" ", int " "spacing" " );
.br

.BI "int im_contrast_surface_raw( IMAGE " "*in" ", IMAGE " "*out" ", int " "half_win_size" ", int " "spacing" " );
.fi
.SH DESCRIPTION
These functions generate an image where the value of each pixel represents the
contrast within a square window of size 2 * half_win_size + 1 centred on the
corresponsing point in the input image.
.PP
The output is sub-sampled by a factor of spacing.
.PP
Input must be single-band uncoded uchar, WIO or PIO.
.PP
Output is single-band uncoded uint, WIO or PIO.
.PP
In
.BR im_contrast_surface(3) ,
pixels beyond the edges of the input image are considered to be have the value
of the nearest pixel which is in the image.
.PP
Alternatively, in
.BR im_contrast_surface_raw(3) ,
pixels within half_win_size of the edge are not calculated, and output is
smaller accordingly.
.SH RETURN VALUE
The functions returns 0 on success and -1 on error.
.SH COPYRIGHT
.br
Copyright 2006, The Nottingham Trent University.
.SH AUTHOR
Tom Vajzovic

