.TH IM_MAXPOS_VEC 3 "01 September 2006"
.SH NAME
 im_maxpos_vec, im_minpos_vec \- Find highest or lowest pixel values
.SH SYNOPSIS
.nf
.B #include <vips/vips.h>
.sp
.BI "int im_maxpos_vec( IMAGE " "*im" ", int " "*xpos" ", int " "*ypos" ", double " "*maxima" ", int " "n" " );
.br

.BI "int im_minpos_vec( IMAGE " "*im" ", int " "*xpos" ", int " "*ypos" ", double " "*minima" ", int " "n" " );
.fi
.SH DESCRIPTION
.B im_maxpos_vec(3)
fills the arrays 
.I xpos 
and 
.I ypos 
with the x and y coordinates of the 
.I n 
pixels in the image
.I im 
which have the highest values.  It writes those values (at double-precsion) 
into the corresponding elements in the array 
.IR maxima ".
.PP
If there is a draw for the 
.IR n "th
pixel, then which of the drawing pixels is used is not defined.
.PP
.B im_minpos_vec(3)
performs the same operation, looking for the lowest valued pixels. 
.SH RETURN VALUE
The functions returns 0 on success and -1 on error.
.SH SEE ALSO
im_maxpos(3), im_minpos(3)
.SH COPYRIGHT
.br
Copyright 2006, The Nottingham Trent University.
Copyright 2006, Tom Vajzovic.
.SH AUTHOR
Tom Vajzovic
