.TH IM_CIRCLE 3 "10 May 1991"
.SH NAME
im_circle \- draws a circle within an image file
.SH SYNOPSIS
.B #include <vips/vips.h>

.B int im_circle(im, cx, cy, radius, intensity)
.br
.B IMAGE *im;
.br
.B int cx, cy;
.br
.B int radius, intensity;
.SH DESCRIPTION
.B im_circle()
draws a circle on top of an image pointed by the image descriptor im.
Input im should be one band unsigned char image.

It must be stressed that a call to this function overwrites the content
of the original image at the points corresponding to the drawn circle.
The centre of the circle is at point (cx, cy) and has radius radius and
the intensity of the produced circle is given by the int intensity (between
0 and 255).  If the circle does not fit in the original image, an error code
is returned.
.SH RETURN VALUE
The function returns 0 on success and -1 on error.
.SH SEE ALSO
im_line(3).
.SH COPYRIGHT
.br
N. Dessipris
.SH AUTHOR
N. Dessipris \- 10/05/1991
