.TH SINES 1 "27 January 1992"
.SH NAME
sines, squares \- creates a spatial sine or square wave form
.SH SYNOPSIS
.B sines image xsize ysize horfreq verfreq

.B squares image xsize ysize horfreq verfreq
.SH DESCRIPTION
.B sines
creates an one band unsigned char
image of the a sine waveform in two dimensions.
The sizes of the created image are xsize by ysize.  The number of
horizontal and vertical spatial frequencies are determined by the variables
horfreq and verfreq respectively.

.B squares
creates an one band unsigned cahr image by thresholding a sine waveform.
.SH SEE\ ALSO
grey(1), im_sines(3X), squares(1).
.SH COPYRIGHT
.br
N. Dessipris
.SH AUTHOR
N. Dessipris \- 27/02/1992
